"""empty message

Revision ID: 2ab66aa637b3
Revises: 907bcb30af4e
Create Date: 2017-07-15 14:25:25.856509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ab66aa637b3'
down_revision = '907bcb30af4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('permission', sa.Integer(), nullable=True))
    op.drop_column('roles', 'permissions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('permissions', sa.INTEGER(), nullable=True))
    op.drop_column('roles', 'permission')
    # ### end Alembic commands ###
